// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxVuza-HdXtDeFNJ_I816Uo28HMNuVmdk',
    appId: '1:717943232591:web:b13baec1636f46fd6c323a',
    messagingSenderId: '717943232591',
    projectId: 'eventra-mobile',
    authDomain: 'eventra-mobile.firebaseapp.com',
    storageBucket: 'eventra-mobile.firebasestorage.app',
    measurementId: 'G-KJNZRFN6GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2eg18QEwQNZBwwgCk-p72rvgrE0IHAJg',
    appId: '1:717943232591:android:2460bfff8f8ece266c323a',
    messagingSenderId: '717943232591',
    projectId: 'eventra-mobile',
    storageBucket: 'eventra-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRZHBQXVOM2Ejh7U4_CYWszVJsZajGSq0',
    appId: '1:717943232591:ios:076ce6ad174b5fae6c323a',
    messagingSenderId: '717943232591',
    projectId: 'eventra-mobile',
    storageBucket: 'eventra-mobile.firebasestorage.app',
    iosBundleId: 'com.example.eventraMobile2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRZHBQXVOM2Ejh7U4_CYWszVJsZajGSq0',
    appId: '1:717943232591:ios:076ce6ad174b5fae6c323a',
    messagingSenderId: '717943232591',
    projectId: 'eventra-mobile',
    storageBucket: 'eventra-mobile.firebasestorage.app',
    iosBundleId: 'com.example.eventraMobile2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxVuza-HdXtDeFNJ_I816Uo28HMNuVmdk',
    appId: '1:717943232591:web:6148b5aa9fbe56c46c323a',
    messagingSenderId: '717943232591',
    projectId: 'eventra-mobile',
    authDomain: 'eventra-mobile.firebaseapp.com',
    storageBucket: 'eventra-mobile.firebasestorage.app',
    measurementId: 'G-8XK1FDD1D3',
  );

}